input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["otel-logs"]
    codec => "json"
    client_id => "logstash-logs-consumer"
    group_id => "logstash-logs-group"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "logstash_internal"
    password => "${LOGSTASH_INTERNAL_PASSWORD}"

    # --- 關閉 Logstash 的強制統一命名，恢復分類 ---
    ilm_enabled => false
    manage_template => false
    index => "logstash-filebeat-8.15.0-%{+YYYY.MM.dd}"
  }
}
