filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log

processors:
  - add_docker_metadata: ~

output.kafka:
  hosts: ["kafka:9092"]
  topic: 'otel-logs'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
