apm-server:
  host: "0.0.0.0:8200"
  rum:
    enabled: true

output.kafka:
  enabled: true
  hosts: ["kafka:9092"]
  topic: "apm"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
